development:
<<<<<<< HEAD:config/platform.yml
    name: VoteReport.in
    url: http://localhost:3008
    iphone_url: http://localhost:3008
    audio_url: http://calls.inaugurationreport.com
    tag: votereport
    tags: votereport,indiavotes09,iv09,election09,india09,vote09,elections09,loksabha
        
test:
    name: VoteReport.in
    url: http://localhost:3008
    iphone_url: http://localhost:3008
    audio_url: http://calls.inaugurationreport.com
    tag: votereport
    tags: votereport,indiavotes09,iv09,election09,india09,vote09,elections09,loksabha

=======
    name: SwiftRiver Iran Elections
    url: http://iranelection.swiftapp.org
    iphone_url: http://iphone.votereport.in
    audio_url: http://calls.votereport.in
    tag: iranelection
    tags: iran09,iranelection,tehran,mousavi
test:
    name: SwiftRiver Iran Elections
    url: http://iranelection.swiftapp.org
    iphone_url: http://iphone.votereport.in
    audio_url: http://calls.votereport.in
    tag: iranelection
    tags: iran09,iranelection,tehran,mousavi    
>>>>>>> ac492602e3b89d525b4e24f2a973b77cc2e2e23e:config/platform.yml
production:
    name: SwiftRiver Iran Elections
    url: http://iranelection.swiftapp.org
    iphone_url: http://iphone.votereport.in
    audio_url: http://calls.votereport.in
    tag: iranelection
    tags: iran09,iranelection,tehran,mousavi
